### ISSUE TITLE
Static and dynamic casts

### ISSUE THREAD

**Issue by opensdh** [jbcoe/polymorphic_value#101]
The infrastructure that supports the `polymorphic_value<T>::polymorphic_value(polymorphic_value<U>&&)` constructor template (which is surprisingly heavy, given that repeated invocations build a linked list of type-conversion objects) could also be used to provide function templates
```cpp
template<class T, class U>
polymorphic_value<T> static_polymorphic_cast(polymorphic_value<U>);
template<class T, class U>
polymorphic_value<T> dynamic_polymorphic_cast(const polymorphic_value<U>&);
template<class T, class U>
polymorphic_value<T> dynamic_polymorphic_cast(polymorphic_value<U>&&);
```
A similar set appeared in R0 of the paper, but the semantics here might be a bit different, mostly because of the possibility of rvalue arguments:
1. `static_polymorphic_cast` would allow a `polymorphic_value<Widget>` known to hold (say) a `Dialog` or `Tooltip` to be converted into a `polymorphic_value<Window>` that would persistently support whatever additional operations associated with `Window`.  (It would avoid creating any new objects, unless a small-buffer optimization intervened!)
1. `dynamic_polymorphic_cast` would let a set of `polymorphic_value<Widget>` be filtered into `polymorphic_value<Window>` and `polymorphic_value</* other */>` sets.

These make sense even with the value-not-pointer interpretation of the class template as a whole.

**Comment by jbcoe** [comment]
Do you have used cases that you can share?

Any extra experience/examples would be really useful.

**Comment by opensdh** [comment]
Not really; I just had to implement something very much like `polymorphic_value` myself that supported serialization (I used the cute old name idea of `some`), and thinking about the complexity/overhead necessary to support the "generalizing" constructor made me realize that it could support more than that (in particular, the inverse of that process).

**Comment by jbcoe** [comment]
Musing on this, these cast operators are impossible for users to add as they require access to internals of `polymorphic_value`. If there is a good motivating use case, then they should be added.

**Comment by jbcoe** [comment]
Closing this issue in the absence of a motivating use case.
