### ISSUE TITLE
A different approach to polymorphic values

### ISSUE THREAD

**Issue by sean-parent** [jbcoe/polymorphic_value#103]
Non an issue - but I thought this thread would be relevant to this group.

https://twitter.com/tvaneerd/status/1502375977598566405

**Comment by jbcoe** [comment]
Thanks Sean - that's very interesting.

We just presented at C++ on Sea https://cpponsea.uk/ and are hoping to resume work on standardisation of `polymorphic_value` and `indirect_value` as a coherent body of vocabulary types.
