### ISSUE TITLE
Comments on general design

### ISSUE THREAD

**Issue by hpesoj** [jbcoe/polymorphic_value#15]
Hi Jonathan. I have discussed the design of `propagate_const` and `polymorphic_value` (previously `indirect`) with your via email and the one the C++ Future Proposals group. I'd like to give my thoughts on the design of `polymorphic_value` again given your recent talk.

### Closed-set polymorphism

You discuss how `polymorphic_value` provides "open-set" polymorphism while `variant` provides "closed-set" polymorphism. I think it more accurate to describe `any` as the open-set counterpart to `variant`, while `polymorphic_value` provides `subtype` polymorphism with value semantics.

### `any`

I think it is useful to think of `polymorphic_value` as an `any` which is constrained by an interface (and thus can provide `operator*` and `operator->`). I think it would be valuable for consistency's sake to copy the design of `any` where there is no reason to do otherwise. With this in mind, I have a few suggestions for changes to `polymorphic_type`.

### Move behaviour

I am uncomfortable with how moving a `polymorphic_value` leaves it "empty". This seems very "smart pointer"-like and is at odds with the behaviour of both `any` and `optional`, which actually _move_ the contained value. The only way they can be "empty" is by default construction (or construction/assignment from `nullopt` in the case of `optional`).

### Construction from `T*`

I think allowing `polymorphic_value` to take ownership of a pointer is another "smart pointer"-like behaviour that should be removed. `any` most likely _could_ support such a feature as well, but it doesn't.

### Memory management

You allow a "deleter" and "copier" to be provided with the adopted pointer. If the move behaviour were changed as suggested above, you would need to add a `mover` as well. However, it would make more sense to instead provide a "newer" and "deleter", with the "newer" taking care of allocating memory and the copy and move operations dealing with the actual moving. That said, I think that the concept of "deleters" et al. are again "smart pointer" concepts to allow custom resource management. I think that allocators would be a far better fit here. You could have the following emplacement constructors:

    template <typename... Args>
    polymorphic_value(in_place_t, Args&&... args);
    template <typename U, typename... Args>
    polymorphic_value(in_place_t, initializer_list<U> il, Args&&... args);
    template <typename... Args>
    polymorphic_value(Allocator const& a, in_place_t, Args&&... args);
    template <typename Allocator, typename U, typename... Args>
    polymorphic_value(Allocator const& a, in_place_t, initializer_list<U> il, Args&&... args);

Then the corresponding emplacement functions:

    template <typename... Args>
    void emplace(Args&&... args);
    template <typename U, typename... Args>
    void emplace(initializer_list<U> il, Args&&... args);
    template <typename... Args>
    void emplace_with_allocator(Allocator const& a, Args&&... args);
    template <typename Allocator, typename U, typename... Args>
    void emplace_with_allocator(Allocator const& a, initializer_list<U> il, Args&&... args);

I realise that `any` doesn't support allocators, but I don't see why it shouldn't.

### Assignment

`polymorphic_value<T>` currently allows assignment from `U` if `U*` is convertible to `T*`. This actually constructs a `T` from the `U`, which I think it very confusing given the aforementioned condition (it seems like it should construct a `U`). I think it is better to construct a `T`, but to enable the function if `T` is constructible from `U`, like with `optional`. I would actually probably only allow _explicit_ construction like this, and not provide the assignment operator (avoids the mistaken assumption that a `U` is constructed).

### Naming

I also think it would be nice to have a single-word name to match `any`, `variant` and `optional` to describe what `polymorphic_value` does. Given that it provides subtype polymorphism, perhaps something like `subtype`?_

**Comment by viboes** [comment]
> Assignment
> 
> polymorphic_value<T> currently allows assignment from U if U* is convertible to T*. This actually constructs a T from the U, which I think it very confusing given the aforementioned condition (it seems like it should construct a U). I think it is better to construct a T, but to enable the function if T is constructible from U, like with optional. I would actually probably only allow explicit construction like this, and not provide the assignment operator (avoids the mistaken assumption that a U is constructed).

I'm missing this assignment from the paper. Could you check again?

**Comment by jbcoe** [comment]
> On 22 Feb 2017, at 17:09, Vicente J. Botet Escriba <notifications@github.com> wrote:
> 
> Assignment
> 
> polymorphic_value currently allows assignment from U if U* is convertible to T*. This actually constructs a T from the U, which I think it very confusing given the aforementioned condition (it seems like it should construct a U). I think it is better to construct a T, but to enable the function if T is constructible from U, like with optional. I would actually probably only allow explicit construction like this, and not provide the assignment operator (avoids the mistaken assumption that a U is constructed).
> 
> I'm missing this assignment from the paper. Could you check again?
> 


There's an updated and incomplete draft here
https://github.com/jbcoe/polymorphic_value/blob/master/draft.md

The assignment from U is declared but not specified.
It will construct a U not a T.

**Comment by jbcoe** [comment]
* Re copiers and deleters:
The desire for a custom copier is driven by real-world use of polymorphic_value where a migration path is required for a class heirarchy which has a virtual `Clone()` method.

The custom deleter is useful in cases where managed objects are cleaned up by special functions (across ABI boundaries etc).

I've not seen any need for custom allocators but they could be accommodated in copiers and deleters if required.

* Re: "polymorphic_value<T> currently allows assignment from U if U* is convertible to T*. This actually constructs a T from the U, which I think it very confusing given the aforementioned condition (it seems like it should construct a U)."

It should indeed construct a U. Where did I mislead you? I think wording is still missing.

* Re moving: Move behaviour is consistent with polymorphic_value needing to be a regular type. I can't move from an abstract base class but polymorphic_value needs to be moveable.

**Comment by jbcoe** [comment]
## Re `std::any`
`std::any` does not solve any of the problems my talk addressed as type info is lost.
I think forcing consistency with a class that does a different job is not a route I want to take. 
If there are functionality gaps that can be addressed, we should update polymorphic_value to fill them.

## Re the name `polymorphic_value`
LEWG bikeshedded the name in Issaquah. I like it. If enough people don't it may get re-bikeshedded.

**Comment by hpesoj** [comment]
### Construction from `U`

I was wrong about what it currently does, and after some consideration I feel that this behaviour is probably the best option.

### Construction from `T*`

Fair enough. I won't continue to argue against this.

### `any`

I don't think that `any` can do the job of `polymorphic_value`. I was just pointing out that it seems more accurate to think of `any` as being the "open-set" counterpart to `variant`, while `polymorphic_value` would be more accurately thought of as an `any` that is constrained by an interface.

And I wouldn't suggest forcing consistency with `any`. I only said that it should be consistent if there is no compelling reason for it not to be. For example, `any` has a `has_value` function while `polymorphic_value` has `operator bool`.

### Move behaviour

I think you misunderstood what I suggested. I simply mean that moving a `polymorphic_value` should move the underlying value (value-like semantics), rather than make it "empty" (smart pointer-like semantics). This is the behaviour of both `any` and `optional` (and `variant`), both of which are regular types.

### Copiers and deleters and allocators

Presumably you are accounting for class hierarchies with a virtual `clone` function where the individual classes are also _not_ copyable? Otherwise `polymorphic_value` will just work. Could you not just require copy operations to be defined in this case?

Do you have a specific example of where a deleter might be used?

If the uses cases are there, I don't necessarily have a problem with copiers and deleters (and movers) since they are type-erased and do not otherwise affect the design of `polymorphic_value`. However, they do very much seem like a _smart pointer_ concept to me. The custom management of _values_ usually seems to be handled by allocators.

### Naming

I won't push this issue, but `polymorphic_value` just seems clunky to me. Why don't we have `any_value`, `variant_value` and `optional_value`?

**Comment by jbcoe** [comment]
I can forgive a bit of clunkiness as `polymorphic_value` is not a lightweight tool.
`variant` and `optional` are cheap enough to be free. If a clunky name gives pause for thought, I'm happy.

Please do push this (or any issue) all you like. Design is not complete and things can be changed!

**Comment by opensdh** [comment]
The move constructor and move-assignment operator for `std::any` do not guarantee that they move the contained object rather than just transferring ownership of (an internal pointer to) it; I suspect implementations do the former only if a SBO is in use.  `std::optional` and `std::variant` obviously must move the contained object.

**Comment by jbcoe** [comment]
Thanks. I think that polymorphic_value should follow std::any in this regard: we don’t want to rule out the use of a small-buffer optimisation.

**Comment by jbcoe** [comment]
This discussion has been useful - thanks for the input. 

Closing the issue for now, feel free to re-open or raise another.
