### ISSUE TITLE
Can we define a `std::polymorphic_value<IComponent1 const>`?

### ISSUE THREAD

**Issue by viboes** [jbcoe/polymorphic_value#18]
It is not clear if we can use  a polymorphic value that allows only to use the const functions of `T`.
This doesn't mean that the variable is const.

**Comment by jbcoe** [comment]
I think the answer is yes. Is this not implied by the specification as written?

**Comment by viboes** [comment]
I was wondering because I don't see any tests and I don't see any mention on the proposal.
But maybe this is evident for others.

**Comment by jbcoe** [comment]
It's not evident and I'd be sad if it were not the case. I'll add tests and explicitly mention that `T` can be `const` in the proposal. PR also welcome!
