### ISSUE TITLE
Can `Copier` and `Deleter` be references?

### ISSUE THREAD

**Issue by viboes** [jbcoe/polymorphic_value#20]
Wondering if the parameters `Copier` and `Deleter` can be references as for `unique_ptr`

> unique_ptr( pointer p, d1 );
> 	(3) 	(depuis C++11)
> 		
> unique_ptr( pointer p, d2 );
> 	(4) 	(depuis C++11)
> 
> 3-4) Construit un objet qui possède std::unique_ptr p, l'initialisation du pointeur stocké avec p et initialiser un D deleter comme ci-dessous (dépend si D est un type référence)
> 
> a) Si D est A type non-référence, les signatures sont:
> 
>     unique_ptr(pointer p, const A& d); 
>     unique_ptr(pointer p, A&& d); 
> 
> b) Si D est une lvalue de type A&-référence, les signatures sont:
> 
>     unique_ptr(pointer p, A& d); 
>     unique_ptr(pointer p, A&& d); 
> 
> c) Si D est une lvalue de type const A&-référence, les signatures sont:
> Original:
> If D is an lvalue-reference type const A&, then the signatures are:
> The text has been machine-translated via Google Translate.
> You can help to correct and verify the translation. Click here for instructions.
> 
>     unique_ptr(pointer p, const A& d); 
>     unique_ptr(pointer p, const A&& d);

**Comment by jbcoe** [comment]
What are the pros and cons here? I was under the impression that pass-by-value was best practice for constructors.

**Comment by viboes** [comment]
Coherency on the standard?

cpp-reference gives two examples for unique_ptr.

>     //D is a left value reference type
>     D d3;
>     std::unique_ptr<Foo, D&> up5(new Foo(), d3); //up3 holds a reference to d3
>     up5.reset();
>  
>     //D is a const left value reference type
>     const D d4;
>     std::unique_ptr<Foo, const D&> up6(new Foo(), d4);
>     up6.reset();

**Comment by jbcoe** [comment]
`shared_ptr` (which `polymorphic_value` is more closely modelled on) passes in its deleter by value. I think we should do the same.

See C++17 draft standard 23.11.2.2.

If LEWG or LWG disagree I'll change to passing `Copier` and `Deleter` by reference.
