### ISSUE TITLE
default_copy return type

### ISSUE THREAD

**Issue by uecasm** [jbcoe/polymorphic_value#37]
Would it not be better to define this like so:

    template <class T>
    struct default_copy
    {
        unique_ptr<T> operator()(const T& t) const
        {
            return make_unique<T>(t);
        }
    };

Returning a `unique_ptr` more accurately conveys the intent to create a new T and return ownership of it.

Or perhaps even something like:

    template <class T, class D = default_delete<T> >
    struct default_copy
    {
        unique_ptr<T, D> operator()(const T& t, D d = D{}) const
        {
            return unique_ptr<T, D>(new T(t), std::move(d));
        }
    };

Though I'm not sure if the extra complexity is worthwhile, and it has more potential for shooting yourself in the foot, so I prefer the former.

**Comment by jbcoe** [comment]
My thinking was that the signature of default_copy should be kept as general as possible as we may want to use polymorphic_value with custom copiers and deleters in contexts where copies are not ownable by a unique_ptr (they may come from a c-api function).

A unique_ptr return type is an interesting idea though. Perhaps I’ll try it out on a branch and see what it simplifies,

**Comment by uecasm** [comment]
Hmm.  In the context of a C API making the copy, it probably does make sense for it to attach the correct deleter at that point as well, so leaning more toward the second one.

Not sure if this is a good idea, but it's an idea: perhaps polymorphic_value could take only one extra copier-or-deleter type parameter instead of both, and detect which.  If a deleter is supplied, then it uses default_copy with that deleter (ie. default_copy<T, D> returns a unique_ptr<T, D> as well).  Otherwise if a copier is supplied, it extracts the deleter type from the unique_ptr return type.

Or maybe that's too complicated.  Another possibility is to have a free helper construction function (like make_polymorphic_value) but that accepts a unique_ptr<T, D>; this would be sufficient to pick up a custom deleter automatically, although not a custom copier.  So a value created externally can be transferred in easily.

**Comment by jbcoe** [comment]
The existing interface is pretty simple. I’d like to keep it that way. If you’ve code examples where surprising and bad things happen, I’ll be happy to make changes.
