### ISSUE TITLE
q: what is the status of the proposal?

### ISSUE THREAD

**Issue by kcris** [jbcoe/polymorphic_value#56]
Hi, 

- this is interesting, what is the status of this proposal?
- any issues with slicing?

thanks
Chris

**Comment by jbcoe** [comment]
On course for C++20

**Comment by kcris** [comment]
hi,

how about slicing issues?

thanks

**Comment by jbcoe** [comment]
What slicing issues did you have in mind?

**Comment by kcris** [comment]
well, passing a Derived instance into a Base instance...by value. This is a problem with values, it slices the derived instance and leads to weird results.

I guess the potential risk exists with polymorphic_value as well.

Derived d;
Base b = d; //slicing: b is not a proper Base nor a proper Derived instance

or

polymorphic_value<Derived> dd;
polymorphic_value<Base> bb = dd; //same slicing potential here

Maybe with polymorphic_value this can be disabled/avoided.

Chris

**Comment by jbcoe** [comment]
I think this is addressed in detail by the proposal.

Have you tried using the linked implementation at all?

Thanks for your interest! Always good to know what can be made clearer.

Jon

**Comment by kcris** [comment]
ohhh, sorry, no I didn't, I just discovered this one
thanks a lot
