### ISSUE TITLE
Update CMake to use modern targets based CMake paradigm

### ISSUE THREAD

**Issue by Twon** [jbcoe/polymorphic_value#57]

**Comment by jbcoe** [comment]
Do you have any references?

This sounds like a great idea in any case!

**Comment by jbcoe** [comment]
Our CI should do that for you.
Feel free to submit and fix.

**Comment by Twon** [comment]
Ok, putting the pull request through now then.  Cheers

**Comment by Twon** [comment]
Changes committed now updating to a modern CMake paradigm.
