### ISSUE TITLE
Add `empty` to in addition to `operator bool`

### ISSUE THREAD

**Issue by ingomueller-net** [jbcoe/polymorphic_value#65]
The current way to check whether the `polymorphic_value` is empty is to cast it to `bool`. This is similar how one could check whether a pointer is "empty" or not. However, the latter is considered mal practice (see [checks from `clang-tidy`](https://clang.llvm.org/extra/clang-tidy/checks/readability-implicit-bool-conversion.html)), among other things because of readibility. Instead, testing for equality with `nullptr` is recommended.

I wonder whether there shouldn't be another way to test for emptiness of `polymorphic_value` as well. `empty` (like [`std::vector`](https://en.cppreference.com/w/cpp/container/vector/empty)) or `has_value` (like [`std::any`](https://en.cppreference.com/w/cpp/utility/any/has_value)) look like solutions to me, but other ideas may be better.

**Comment by ingomueller-net** [comment]
It just occured to me that exposing `ptr()` would be another solution to my use case and could be useful in other cases as well. If one needs to pass a raw pointer to some legacy code (while guaranteeing the lifetime of the pointee manually), we need to access the internal pointer, which I currently do not see how to get it.

**Comment by ingomueller-net** [comment]
Another related functionality are down casts. There are cases where you have a `Base` but know that the runtime time is really `Derived` and want to use it as such. Getting `ptr_` would make this possible with a `dynamic_cast` or `boost::polymorphic_pointer_downcast`, but something similar to [`std::any_cast`](https://en.cppreference.com/w/cpp/utility/any/any_cast) could also be a solution.

**Comment by jbcoe** [comment]
It's not clear if we should add `empty` like `std::vector` or `has_value` like `std::any` and `std::optional`. It rather depends on what polymorphic is most like.

In either case it can be added later as an NB comment or in a revised C++ standard library.
