### ISSUE TITLE
Expose underlying pointer

### ISSUE THREAD

**Issue by ingomueller-net** [jbcoe/polymorphic_value#68]
This is a side point from #65.

The underlying pointer should be exposed through `get()` or similar. There are two uses cases: First, one might need to pass a raw pointer to legacy code (while guaranteeing the lifetime of the pointee manually). The second use case are downcasts: You might have a Base but know at the runtime time that it is really Derived and want to use it as such. Getting `get()` would make this possible with a `dynamic_cast` or `boost::polymorphic_pointer_downcast`, but something similar to [`std::any_cast`](https://en.cppreference.com/w/cpp/utility/any/any_cast) could also be a solution.

**Comment by jbcoe** [comment]
Thanks for raising this.

The pointer-like early design of polymorphic_value (then cloned_ptr) was not well-liked by the C++ library design group. Pointer-like cast functions and the pointer accessing `get()` method were removed.

I can't deny the potential utility but I have followed the recommended design direction.

You can use `std::addressof(*pv)` to get a raw pointer from a polymorphic value if you really need to.

If you have an extended real-world example I'd be very keen to see it. Design can always change in the light of usage experience and evidence.
