### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by enjoysmath** [jbcoe/polymorphic_value#71]
Hello,

I've installed C++14 (for make_unique etc) through MSVC 2017 kit for Qt5.  Using QtCreator.

Using this header in my code now.

Just wanted to say thank you for coding it!

The license is present in the header, and I will abide by it if I start selling or releasing my code.

**Comment by jbcoe** [comment]
Thanks for the kind words! 

Please let me know if you have any feedback, good or bad.
