### ISSUE TITLE
Add more wording to define the copier and deleter

### ISSUE THREAD

**Issue by jbcoe** [jbcoe/polymorphic_value#8]

**Comment by viboes** [comment]
The wording associated to the construction from pointer seems to contain most of what is needed.

> Preconditions: c and d are copy constructible. If p is non-null then the expression c(*p) shall return an object of type U*. The expression d(p) shall be well formed, shall have well defined behavior, and shall not throw exceptions. Either U and T must be the same type, or the dynamic and static type of U must be the same.

BTW, this section doesn't corresponds to a precondition clause but a requires clause.

**Comment by jbcoe** [comment]
Thanks!
