### ISSUE TITLE
public inheritance from std::exception

### ISSUE THREAD

**Issue by BenjaminBeichler** [jbcoe/polymorphic_value#80]
Is there any reason, why you do not publicly derive from std::exception? 

https://github.com/jbcoe/polymorphic_value/blob/c933d35e08d7894ea8f1f90c86fe76df3245e156/polymorphic_value.h#L149

My compiler is warning me about that :-)

**Comment by jbcoe** [comment]
Just an oversight I think.
Patches welcome!

**Comment by Twon** [comment]
Changes now committed.  Thanks @BenjaminBeichler!
