### ISSUE TITLE
Question: Why explicit constructors?

### ISSUE THREAD

**Issue by githubuser0xFFFF** [jbcoe/polymorphic_value#87]
Hi,

I just wanted to say that I really like the `polymorphic_value` class - it adds so much value to C++ because now there is no need to implement constructors and assignment operators for classes with pointers or polymorphic pointer - that is great.

I'm a big fan of the pimpl idiom and for me the `polymorphic_value` is perfect for implementing the private pimpl pointer because it ensures proper copying of the internal data - so a big thank you.

We just updated to the latest `polymorphic_value` and noticed, that the contructors are explicit now. That means the following code:

```c++
CComposition::CComposition()
	: d_ptr(make_polymorphic_value<CComposition::Private>())
{

}


void CComposition::setDerivedPtr(CDerived* Value)
{
	PIMPL_D(CComposition);
	d->DerivedPtr = *Value;
}
```

changed into this code now:

```c++
CComposition::CComposition()
	: d_ptr(make_polymorphic_value<CComposition::Private>())
{

}


void CComposition::setDerivedPtr(CDerived* Value)
{
	PIMPL_D(CComposition);
	d->DerivedPtr = polymorphic_value<CBase>(polymorphic_value<CDerived>(Value));
}
```

So assigning a derived value pointer to a base value pointer is more verbose now and not so elegant anymore. Just out of interest, what was the reson for making the constructors explicit or what dangers are inherent in a non-explicit constructor?

Thank you.

**Comment by Twon** [comment]
Hi, glad to hear you are enjoying polymorphic_value.  With any luck, it may make it into C++ 23 for inclusion as part of the standard library (LWEG ran out of time to include it in C++ 20).

In short, at the 2018 San-Diego ISO C++ meeting, the Library Evolution Work Group requested that this change was made to the design of `polymorphic_value` to avoid accidental implicit conversion taking place.
Please see [No Implicit conversions](https://github.com/jbcoe/polymorphic_value/blob/master/draft.md#no-implicit-conversions) for a discussion around this.

In your use case, it looks like you are constructing a temporary `polymorphic_value` which you then move from immediately.  I might simplify this to just use the converting constructor as such:
```
	d->DerivedPtr = polymorphic_value<CBase>(Value);
```

I'll close this for now, but please re-open if you have further comments.

**Comment by Twon** [comment]
Btw, it looks like your use case for the PIMPL does involve polymorphism.  However, if you are using the PIMPL pattern without polymorphism then I'd recommend looking at [indirect_value](https://github.com/jbcoe/indirect_value/) which we have proposed for inclusion into C++23 specifically for handling the PIMPL usecase: [indirect_value: A Free-Store-Allocated Value Type For C++](http://www.open-std.org/jtc1/sc22/wg21/docs/papers/2020/p1950r0.html).

**Comment by githubuser0xFFFF** [comment]
Thank you - really cool. Yes indeed, my PIMPL implementation involves polymorphism and is inspired by the Qt framework. I just replaced the internal plain d pointers with your `polymorphic_value` type and it made the use of private data pointers so much easier: https://github.com/githubuser0xFFFF/polypimp
