### ISSUE TITLE
object slicing solved?

### ISSUE THREAD

**Issue by zeyangl** [jbcoe/polymorphic_value#89]
I find the polymorphic_value concept very interesting and is considering using it in my project. As I was looking around for similar concepts I found this post by Herb Sutter mentioning the polymorphic_value in the context of object slicing. 
https://herbsutter.com/2019/10/03/gotw-ish-solution-the-clonable-pattern/
He seems to think polymorphic_value can't handle object slicing but my understading of the implemention and the related talk by Sean Parent tells me that shouldn't be the case, and some testing confirms it. Just want double check if object slicing is an explicitly considered case.

**Comment by cskrisz** [comment]
Herb said:

> with nonintrusive approaches users can still create objects of the types directly and slice them:
> ```
> D d;
> B b = d;                                // oops, still works
> ```
> Only an intrusive solution can make the copy constructor nonpublic or suppressed

So yes, object slicing solved if you use `polymorphic_value`, but it won't prevent users from doing the above.
